"""End-to-end golden workflow tests.

Drives the public CLI only (``instantiate``, ``validate``, ``inject``) as a
subprocess, the same way a real caller would, and never imports the
implementation module. Golden files under ``tests/golden`` are themselves
generated by that same CLI, so this test proves the CLI's public surface
produces stable, valid output, not that its private helpers behave a
particular way.

Line-ending normalization (CRLF/CR -> LF) is applied only to the in-memory
text used for equality comparison against the checked-in golden files; the
golden files and input fixtures on disk are never rewritten by this test.

Golden-equality is one check among several: each workflow also asserts
concrete, golden-independent invariants (worksheet/window pairing, the
target datasource and its fields, absence of donor residue or unresolved
tokens, and — for injection — preservation of the pre-existing workbook's
marker comment and surrounding bytes), so a golden file that accidentally
encoded a bug would not be the only thing standing between this suite and a
regression.

Every test independently confirms, in its own teardown, that the input
fixtures it read are byte-identical to their pinned SHA-256 hashes. Because
that check runs per test rather than once at import or in a single shared
test, it is order-independent: any test that ran before or after it could
not have caused it to pass or fail.
"""

from __future__ import annotations

import hashlib
import re
import shutil
import subprocess
import sys
import tempfile
import unittest
import xml.etree.ElementTree as ET
from pathlib import Path

PLUGIN = Path(__file__).resolve().parents[1]
FIXTURES = PLUGIN / "tests/fixtures"
GOLDEN = PLUGIN / "tests/golden"
CLI = PLUGIN / "scripts/tableau_resources.py"

TARGET_DATASOURCE_DEFINITION = FIXTURES / "target-datasource.xml"
EXISTING_WORKBOOK = FIXTURES / "existing-workbook.twb"

# Pinned literals rather than hashes computed at import time: a corrupted or
# silently-edited fixture must fail against a fixed expectation, not against
# whatever the fixture happened to contain when the test process started.
FIXTURE_SHA256 = {
    TARGET_DATASOURCE_DEFINITION: (
        "1764d536754c3e3befc9b4ce31d7bbe3954a740b3c1dd837178ac2a7f7bec754"
    ),
    EXISTING_WORKBOOK: (
        "12497ca0197a3955ba3b135b4b5bbae862d082f92d78ea7ab2b30fe88a2cffe4"
    ),
}

FIXTURE_DATASOURCE = "federated.0fixture1sales2data"
DONOR_DATASOURCE = "Sample - Superstore"
EXISTING_WORKBOOK_MARKER = "<!-- preserve-this-byte-for-byte -->"
TEMPLATE_TOKEN_RE = re.compile(r"\{\{[^}]+\}\}")


def _read_normalized(path: Path) -> str:
    """Read a UTF-8 text file and normalize CRLF/CR line endings to LF.

    Reads raw bytes and decodes explicitly rather than relying on
    ``Path.read_text``'s platform-dependent universal-newline translation, so
    normalization is real and identical on every platform this test runs on.
    Only the returned string is normalized; the file on disk is untouched.
    """
    text = path.read_bytes().decode("utf-8")
    return text.replace("\r\n", "\n").replace("\r", "\n")


class EndToEndGoldenWorkflowTest(unittest.TestCase):
    maxDiff = None

    def setUp(self) -> None:
        self.tmp = Path(tempfile.mkdtemp())
        self.addCleanup(shutil.rmtree, self.tmp, ignore_errors=True)

    def tearDown(self) -> None:
        # Runs after every test method, independent of test order, so a
        # fixture mutated by one workflow can never be masked by another
        # test happening to run first and re-reading a still-clean copy.
        for path, expected_digest in FIXTURE_SHA256.items():
            digest = hashlib.sha256(path.read_bytes()).hexdigest()
            self.assertEqual(
                digest,
                expected_digest,
                f"fixture {path} changed during {self.id()}",
            )

    def run_cli(self, *args: str) -> subprocess.CompletedProcess[str]:
        return subprocess.run(
            [sys.executable, str(CLI), *args],
            encoding="utf-8",
            capture_output=True,
            check=False,
        )

    def assert_validates_clean(self, workbook: Path) -> None:
        result = self.run_cli("validate", "--input", str(workbook))
        self.assertEqual(result.returncode, 0, result.stdout)
        self.assertEqual(result.stdout.strip(), "[]")

    def assert_matches_golden(self, generated: str, golden_name: str) -> str:
        golden_path = GOLDEN / golden_name
        golden = _read_normalized(golden_path)
        self.assertEqual(
            generated,
            golden,
            f"generated workbook does not match golden file {golden_path}",
        )
        return golden

    def assert_no_donor_residue_or_unresolved_tokens(
        self, text: str, *, label: str
    ) -> None:
        self.assertNotIn(
            DONOR_DATASOURCE, text, f"{label} still references the donor datasource"
        )
        token = TEMPLATE_TOKEN_RE.search(text)
        self.assertIsNone(
            token,
            f"{label} contains an unresolved template token: "
            f"{token.group(0) if token else ''}",
        )

    def assert_worksheet_window_pairing(
        self, root: ET.Element, expected_names: list[str]
    ) -> None:
        worksheets = [
            item.get("name") for item in root.findall("worksheets/worksheet")
        ]
        windows = [item.get("name") for item in root.findall("windows/window")]
        self.assertEqual(worksheets, expected_names)
        self.assertEqual(windows, expected_names)
        for window in root.findall("windows/window"):
            self.assertEqual(window.get("class"), "worksheet")

    def assert_view_datasource(
        self,
        root: ET.Element,
        worksheet_name: str,
        *,
        name: str,
        caption: str,
    ) -> None:
        """Check the view names the target internally and labels it readably."""
        for worksheet in root.findall("worksheets/worksheet"):
            if worksheet.get("name") != worksheet_name:
                continue
            declared = worksheet.find("table/view/datasources/datasource")
            self.assertIsNotNone(declared)
            self.assertEqual(declared.get("name"), name)
            self.assertEqual(declared.get("caption"), caption)
            return
        self.fail(f"no worksheet named {worksheet_name}")

    def assert_dependency_types(
        self,
        root: ET.Element,
        worksheet_name: str,
        expected: dict[str, tuple[str, str]],
    ) -> None:
        """Check mapped dependency columns carry the target's declared types.

        Guards the defect where a rewritten declaration kept the donor's
        datatype, which described a field the target does not have.
        """
        for worksheet in root.findall("worksheets/worksheet"):
            if worksheet.get("name") != worksheet_name:
                continue
            declared = {
                column.get("name"): (
                    column.get("datatype"),
                    column.get("user-datatype"),
                    column.get("role"),
                )
                for column in worksheet.iter("column")
            }
            for field, (datatype, role) in expected.items():
                self.assertEqual(
                    declared.get(field),
                    (datatype, datatype, role),
                    f"{field} does not carry the target's declared type",
                )
            return
        self.fail(f"no worksheet named {worksheet_name}")

    def assert_target_datasource_fields(
        self, root: ET.Element, datasource_name: str, expected_fields: set[str]
    ) -> None:
        datasources = {
            datasource.get("name"): datasource
            for datasource in root.findall("datasources/datasource")
        }
        self.assertIn(datasource_name, datasources)
        fields = {
            column.get("name")
            for column in datasources[datasource_name].findall("column")
        }
        self.assertEqual(fields, expected_fields)

    def test_instantiate_bar_chart_matches_golden_and_validates(self) -> None:
        output = self.tmp / "insights-bar.twb"
        result = self.run_cli(
            "instantiate",
            "insights__bar_chart",
            "--datasource-definition",
            str(TARGET_DATASOURCE_DEFINITION),
            "--output",
            str(output),
            "--worksheet-name",
            "ARR by Offering",
            "--map",
            "ARR=Revenue",
            "--map",
            "Close Date=Transaction Date",
            "--map",
            "Product=Offering",
            "--param",
            "DATE_MIN=2026-01-01",
            "--param",
            "DATE_MAX=2026-06-30",
            "--param",
            "DIRECTION=DESC",
        )
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertTrue(output.exists())
        self.assert_validates_clean(output)

        generated = _read_normalized(output)
        self.assert_matches_golden(generated, "insights-bar.twb")

        # --- invariants independent of golden equality ---
        root = ET.fromstring(generated)
        self.assert_worksheet_window_pairing(root, ["ARR by Offering"])
        self.assert_target_datasource_fields(
            root, "Sales Data", {"[Revenue]", "[Transaction Date]", "[Offering]"}
        )
        self.assert_view_datasource(
            root, "ARR by Offering", name="Sales Data", caption="Sales Data"
        )
        # The donor's ARR is an integer; the target's Revenue is a real.
        self.assert_dependency_types(
            root,
            "ARR by Offering",
            {
                "[Revenue]": ("real", "measure"),
                "[Transaction Date]": ("date", "dimension"),
                "[Offering]": ("string", "dimension"),
            },
        )
        self.assert_no_donor_residue_or_unresolved_tokens(
            generated, label="generated bar-chart workbook"
        )

    def test_inject_line_chart_matches_golden_and_validates(self) -> None:
        original = _read_normalized(EXISTING_WORKBOOK)
        output = self.tmp / "insights-line-injected.twb"
        result = self.run_cli(
            "inject",
            "insights__line_chart",
            "--input",
            str(EXISTING_WORKBOOK),
            "--output",
            str(output),
            "--worksheet-name",
            "ARR Trend",
            "--datasource",
            FIXTURE_DATASOURCE,
            "--map",
            "ARR=Revenue",
            "--map",
            "Close Date=Transaction Date",
        )
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertTrue(output.exists())
        self.assert_validates_clean(output)

        generated = _read_normalized(output)
        self.assert_matches_golden(generated, "insights-line-injected.twb")

        # --- invariants independent of golden equality ---
        root = ET.fromstring(generated)
        self.assert_worksheet_window_pairing(
            root, ["Existing Sheet", "ARR Trend"]
        )
        self.assert_target_datasource_fields(
            root,
            FIXTURE_DATASOURCE,
            {"[Revenue]", "[Transaction Date]", "[Offering]"},
        )
        # The target's internal name is a federated hash, so the view has to
        # label it with the datasource's own caption instead.
        self.assert_view_datasource(
            root, "ARR Trend", name=FIXTURE_DATASOURCE, caption="Sales Data"
        )
        self.assert_dependency_types(
            root,
            "ARR Trend",
            {
                "[Revenue]": ("real", "measure"),
                "[Transaction Date]": ("date", "dimension"),
            },
        )
        self.assert_no_donor_residue_or_unresolved_tokens(
            generated, label="generated line-chart-injected workbook"
        )

        # --- injected-workbook marker and unrelated bytes preserved ---
        self.assertIn(EXISTING_WORKBOOK_MARKER, generated)
        prefix_end = original.index("</worksheets>")
        insertion_point = generated.index("<worksheet name='ARR Trend'>")
        self.assertEqual(original[:prefix_end], generated[:insertion_point])
        tail = original[original.index("</windows>") :]
        self.assertTrue(generated.endswith(tail))


if __name__ == "__main__":
    unittest.main()
